
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0zdywn"
      binary: "D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0zdywn"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-0zdywn
        
        Run Build Command(s):D:/Program Files/CLion-2023.2.1.win/bin/ninja/win/x64/ninja.exe -v cmTC_d9f5b && [1/2] "D:\\Program Files\\CLion-2023.2.1.win\\bin\\mingw\\bin\\gcc.exe"   -fdiagnostics-color=always   -v -o CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj -c "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c"
        Using built-in specs.
        COLLECT_GCC=D:\\Program Files\\CLion-2023.2.1.win\\bin\\mingw\\bin\\gcc.exe
        Target: x86_64-w64-mingw32
        Configured with: ../gcc-13.1.0/configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --build=x86_64-alpine-linux-musl --prefix=/win --enable-checking=release --enable-fully-dynamic-string --enable-languages=c,c++ --with-arch=nocona --with-tune=generic --enable-libatomic --enable-libgomp --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --enable-seh-exceptions --enable-shared --enable-static --enable-threads=posix --enable-version-specific-runtime-libs --disable-bootstrap --disable-graphite --disable-libada --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-libquadmath --disable-lto --disable-nls --disable-multilib --disable-rpath --disable-symvers --disable-werror --disable-win32-registry --with-gnu-as --with-gnu-ld --with-system-libiconv --with-system-libz --with-gmp=/win/makedepends --with-mpfr=/win/makedepends --with-mpc=/win/makedepends
        Thread model: posix
        Supported LTO compression algorithms: zlib
        gcc version 13.1.0 (GCC) 
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=nocona' '-dumpdir' 'CMakeFiles/cmTC_d9f5b.dir/'
         D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/13.1.0/cc1.exe -quiet -v -iprefix D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/ -D_REENTRANT D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeCCompilerABI.c -quiet -dumpdir CMakeFiles/cmTC_d9f5b.dir/ -dumpbase CMakeCCompilerABI.c.c -dumpbase-ext .c -mtune=generic -march=nocona -version -fdiagnostics-color=always -o C:\\Users\\13749\\AppData\\Local\\Temp\\ccP2lStF.s
        GNU C17 (GCC) version 13.1.0 (x86_64-w64-mingw32)
        	compiled by GNU C version 13.1.0, GMP version 6.2.1, MPFR version 4.2.0-p4, MPC version 1.3.1, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring duplicate directory "D:/Program Files/CLion-2023.2.1.win/bin/mingw/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/13.1.0/include"
        ignoring nonexistent directory "/win/include"
        ignoring duplicate directory "D:/Program Files/CLion-2023.2.1.win/bin/mingw/lib/gcc/../../include"
        ignoring duplicate directory "D:/Program Files/CLion-2023.2.1.win/bin/mingw/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/13.1.0/include-fixed"
        ignoring duplicate directory "D:/Program Files/CLion-2023.2.1.win/bin/mingw/lib/gcc/../../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/include"
        ignoring nonexistent directory "/mingw/include"
        #include "..." search starts here:
        #include <...> search starts here:
         D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/include
         D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../include
         D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/include-fixed
         D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/include
        End of search list.
        Compiler executable checksum: 2aa4fcf5c9208168c5e2d38a58fc2a97
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=nocona' '-dumpdir' 'CMakeFiles/cmTC_d9f5b.dir/'
         as -v -o CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj C:\\Users\\13749\\AppData\\Local\\Temp\\ccP2lStF.s
        GNU assembler version 2.40 (x86_64-w64-mingw32) using BFD version (GNU Binutils) 2.40
        COMPILER_PATH=D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/13.1.0/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../libexec/gcc/
        LIBRARY_PATH=D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/../lib/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../lib/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../../x86_64-w64-mingw32/lib/;D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/../lib/gcc/x86_64-w64-mingw32/13.1.0/../../../
        COLLECT_GCC_OPTIONS='-fdiagnostics-color=always' '-v' '-o' 'CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj' '-c' '-mtune=generic' '-march=nocona' '-dumpdir' 'CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.'
        
        CreateProcess failed. Command attempted:
        "cmd.exe /C "cd . && "D:\\Program Files\\CLion-2023.2.1.win\\bin\\mingw\\bin\\gcc.exe"  -v CMakeFiles/cmTC_d9f5b.dir/CMakeCCompilerABI.c.obj -o cmTC_d9f5b.exe -Wl,--out-implib,libcmTC_d9f5b.dll.a -Wl,--major-image-version,0,--minor-image-version,0   && cd .""
        ninja: fatal: CreateProcess: 请求的操作需要提升。\x0d
        
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Program Files/CLion-2023.2.1.win/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: D:/Program Files/CLion-2023.2.1.win/bin/mingw/bin/gcc.exe"
    directories:
      source: "D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-85j980"
      binary: "D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-85j980"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-85j980
        
        Run Build Command(s):D:/Program Files/CLion-2023.2.1.win/bin/ninja/win/x64/ninja.exe -v cmTC_c41b1 && [1/2] "D:\\Program Files\\CLion-2023.2.1.win\\bin\\mingw\\bin\\gcc.exe"   -fdiagnostics-color=always -o CMakeFiles/cmTC_c41b1.dir/testCCompiler.c.obj -c D:/workspace/C++DEMO/poject0/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-85j980/testCCompiler.c
        
        CreateProcess failed. Command attempted:
        "cmd.exe /C "cd . && "D:\\Program Files\\CLion-2023.2.1.win\\bin\\mingw\\bin\\gcc.exe"   CMakeFiles/cmTC_c41b1.dir/testCCompiler.c.obj -o cmTC_c41b1.exe -Wl,--out-implib,libcmTC_c41b1.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd .""
        ninja: fatal: CreateProcess: 请求的操作需要提升。\x0d
        
        
      exitCode: 1
...
